### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mamat-rahmat** [silalahi/slim-logger#2]
Hi, I don't see a license choice for this repository, or https://github.com/silalahi/slim-logger.
Lisence is important to state what is permitted and not.

I'm suggesting a MIT lisence for this. http://choosealicense.com/licenses/mit/
I'm also suggesting create a LISENCE file, because that makes that more accessible to humans and computers

**Comment by silalahi** [comment]
Thanks mamat, 

I will update for lisence file.
